{{- if not .Values.graylog.existingRootSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graylog.fullname" . }}
  labels:
{{ include "graylog.metadataLabels" . | indent 4 }}
{{- if .Values.graylog.secret.annotations }}
  annotations:
    {{- toYaml .Values.graylog.secret.annotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  graylog-root-username: {{ .Values.graylog.rootUsername | b64enc | quote }}
  {{- $password := (include "graylog.password" .) }}
  graylog-password-secret: {{ $password | b64enc | quote }}
  graylog-password-sha2: {{ $password | sha256sum | b64enc | quote }}
{{- end }}
