apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "graylog.fullname" . }}
  labels:
{{ include "graylog.metadataLabels" . | indent 4 }}
{{- with .Values.graylog.customLabels }}
{{ . | toYaml | indent 4 }}
{{- end }}
spec:
  serviceName: {{ template "graylog.service.headless.name" . }}
  replicas: {{ .Values.graylog.replicas }}
  selector:
    matchLabels:
{{ include "graylog.selectorLabels" . | indent 6 }}
  updateStrategy:
    type: {{ .Values.graylog.updateStrategy }}
  template:
    metadata:
      labels:
{{ include "graylog.metadataLabels" . | indent 8 }}
{{- with .Values.graylog.customLabels }}
{{ . | toYaml | indent 8 }}
{{- end }}
      annotations:
      {{- if .Values.graylog.podAnnotations }}
      {{- range $key, $value := .Values.graylog.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.graylog.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9833"
        prometheus.io/path: "/api/metrics/prometheus"
      {{- end }}
    spec:
      serviceAccountName: {{ template "graylog.serviceAccountName" . }}
{{- if .Values.graylog.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.graylog.nodeSelector | indent 8 }}
{{- end }}
{{ template "graylog.affinity" . }}
{{- if .Values.graylog.tolerations }}
      tolerations:
{{ toYaml .Values.graylog.tolerations | indent 8 }}
{{- end }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
{{- if .Values.graylog.priorityClassName }}
      priorityClassName: {{ .Values.graylog.priorityClassName }}
{{- end }}
      securityContext:
        {{- toYaml .Values.graylog.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "setup"
          image: {{ .Values.graylog.init.image.repository | default "busybox" }}
          imagePullPolicy: {{ .Values.graylog.init.image.pullPolicy | default "IfNotPresent" }}
          # Graylog journal will recursive in every subdirectories. Any invalid format directories will cause errors
          command:
            - /bin/sh
            - -c
            - |
              rm -rf /usr/share/graylog/data/journal/lost+found
            {{- if .Values.graylog.journal.deleteBeforeStart }}
              rm -rf /usr/share/graylog/data/journal/graylog2-committed-read-offset
              rm -rf /usr/share/graylog/data/journal/messagejournal-0
              rm -rf /usr/share/graylog/data/journal/recovery-point-offset-checkpoint
            {{- end }}
              {{- if .Values.graylog.init.kubectlLocation }}
              wget {{ .Values.graylog.init.kubectlLocation }} -O /k8s/kubectl
              {{- else }}
              wget https://storage.googleapis.com/kubernetes-release/release/{{ .Values.graylog.init.kubectlVersion | default .Capabilities.KubeVersion.Version }}/bin/linux/amd64/kubectl -O /k8s/kubectl
              {{- end }}
              chmod +x /k8s/kubectl

              GRAYLOG_HOME=/usr/share/graylog
              chown -R 1100:1100 ${GRAYLOG_HOME}/data/
          env:
            {{- range $key, $value := .Values.graylog.init.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: journal
              mountPath: /usr/share/graylog/data/journal
            - name: kubectl
              mountPath: /k8s
{{- if .Values.graylog.init.resources }}
          resources:
{{ toYaml .Values.graylog.init.resources | indent 12 }}
{{- end }}
{{- if .Values.graylog.extraInitContainers }}
{{ toYaml .Values.graylog.extraInitContainers | indent 8 }}
{{- end }}
      containers:
        - name: graylog-server
          image: "{{ .Values.graylog.image.repository }}:{{ .Values.graylog.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.graylog.image.pullPolicy | quote }}
          command:
            - /entrypoint.sh
          env:
            - name: GRAYLOG_SERVER_JAVA_OPTS
              {{- $javaOpts := .Values.graylog.javaOpts }}
              {{- if .Values.graylog.heapSize }}
              value: "{{ $javaOpts }} {{ printf "-Xms%s -Xmx%s" .Values.graylog.heapSize .Values.graylog.heapSize}}"
              {{- else }}
              value: "{{ $javaOpts }} -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
              {{- end }}
            - name: GRAYLOG_PASSWORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.graylog.existingRootSecret | default (include "graylog.fullname" .) }}
                  key: graylog-password-secret
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.graylog.existingRootSecret | default (include "graylog.fullname" .) }}
                  key: graylog-password-sha2
            {{- if .Values.graylog.elasticsearch.uriSecretKey }}
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.graylog.elasticsearch.uriSecretName | default (printf "%s-es" (include "graylog.fullname" .)) }}
                  key: {{ .Values.graylog.elasticsearch.uriSecretKey }}
            {{- end }}
            {{- if .Values.graylog.mongodb.uriSecretKey }}
            - name: GRAYLOG_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.graylog.mongodb.uriSecretName | default (printf "%s-mongodb" (include "graylog.fullname" .)) }}
                  key: {{ .Values.graylog.mongodb.uriSecretKey }}
            {{- end }}
            {{- range $key, $value := .Values.graylog.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.graylog.envRaw }}
            {{- with .Values.graylog.envRaw }}
                {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.graylog.securityContext | nindent 12 }}
          ports:
            - containerPort: 9000
              name: graylog
          {{- range .Values.graylog.service.ports }}
            - containerPort: {{ .port }}
              name: {{ .name}}
              protocol: {{ .protocol }}
          {{- end }}
          {{- with .Values.graylog.input }}
          {{- if .udp }}
          {{- range .udp.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
              protocol: UDP
          {{- end }}
          {{- end }}
          {{- if .tcp }}
          {{- range .tcp.ports }}
            - containerPort: {{ .port }}
              name: {{ .name }}
              protocol: TCP
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.graylog.resources | indent 12 }}
          startupProbe:
            httpGet:
              path: /api/system/lbstatus
              port: 9000
            {{- if .Values.graylog.tls.enabled }}
              scheme: HTTPS
            {{- end }}
            periodSeconds: {{ .Values.graylog.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.graylog.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.graylog.startupProbe.successThreshold }}
            timeoutSeconds: {{ .Values.graylog.startupProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /api/system/lbstatus
              port: 9000
            {{- if .Values.graylog.tls.enabled }}
              scheme: HTTPS
            {{- end }}
            initialDelaySeconds: {{ .Values.graylog.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.graylog.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.graylog.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.graylog.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.graylog.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /api/system/lbstatus
              port: 9000
            {{- if .Values.graylog.tls.enabled }}
              scheme: HTTPS
            {{- end }}
            initialDelaySeconds: {{ .Values.graylog.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.graylog.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.graylog.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.graylog.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.graylog.readinessProbe.timeoutSeconds }}
          volumeMounts:
            - name: journal
              mountPath: /usr/share/graylog/data/journal
            - name: config
              mountPath: /usr/share/graylog/config
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
          {{- if .Values.graylog.serverFiles }}
            - name: files
              mountPath: /etc/graylog/server
          {{- end }}
            - name: kubectl
              mountPath: /k8s
          {{- if .Values.graylog.extraVolumeMounts }}
          {{ toYaml .Values.graylog.extraVolumeMounts | nindent 12 }}
          {{- end }}
          {{ $graylogVersion := .Values.graylog.image.tag | default .Chart.AppVersion }}
          {{- if semverCompare "< 4.2.0-0" ( $graylogVersion ) }}
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -ec
                  - |
                    ROOT_PASSWORD=`/k8s/kubectl get secret {{ template "graylog.fullname" . }} -o "jsonpath={.data['graylog-password-secret']}" | base64 -d`
                    curl {{ if .Values.graylog.tls.enabled }}-k{{ end }} -XPOST -sS \
                      -u "{{ .Values.graylog.rootUsername }}:${ROOT_PASSWORD}" \
                      -H "X-Requested-By: {{ template "graylog.fullname" . }}" \
                      {{ template "graylog.formatUrl" (list . "localhost:9000/api/system/shutdown/shutdown") }}
          {{- end }}
      {{- if .Values.graylog.sidecarContainers }}
        {{ toYaml .Values.graylog.sidecarContainers | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ default 30 .Values.graylog.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          configMap:
            name: {{ template "graylog.fullname" . }}
            items:
              - key: graylog.conf
                path: graylog.conf
                mode: 292 # 0444
              - key: log4j2.xml
                path: log4j2.xml
                mode: 292 # 0444
        - name: entrypoint
          configMap:
            name: {{ template "graylog.fullname" . }}
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
                mode: 365 # 0555
        {{- if .Values.graylog.serverFiles }}
        - name: files
          configMap:
            name: {{ template "graylog.fullname" . }}-files
        {{- end }}
        - name: kubectl
          emptyDir: {}
        {{- if .Values.graylog.extraVolumes }}
        {{ toYaml .Values.graylog.extraVolumes | nindent 8 }}
        {{- end }}
{{- if not .Values.graylog.persistence.enabled }}
        - name: journal
          emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: journal
      spec:
        accessModes:
          - {{ .Values.graylog.persistence.accessMode | quote }}
      {{- if .Values.graylog.persistence.storageClass }}
      {{- if (eq "-" .Values.graylog.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.graylog.persistence.storageClass }}"
      {{- end }}
      {{- end }}
        resources:
          requests:
            storage: "{{ .Values.graylog.persistence.size }}"
{{- end }}
